-- Hyprland 0.55+
require("monitors")
require("plugins")
require("binds")
require("env")
require("animations")
require("layouts")
require("window_rules")
require("layer_rules")
require("settings")
require("scripts.noctalia_bar")
require("scripts.trailing_empty")
require("startup")
